version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - export GOMOD=$CODEBUILD_SRC_DIR/go.mod:GOMOD
      - export GOPATH="/go"
  build:
    commands:
      - echo "Compilation context:"
      - echo "CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION"
      - make tools
      - make release
    finally:
      - echo "Built artifacts:"
      - ls -lah ./bin/local
      - ./bin/local/ecs-preview-amd64 --version
  post_build:
    commands:
      - VERSION=`./bin/local/ecs-preview-amd64 --version`
      - VERSION=`echo $VERSION | grep -oE "[^ ]+$"`
      - COMMIT_VERSION=`git rev-parse --short HEAD`
      - echo "Creating latest and version-tagged artifacts..."
      - mv ./bin/local/ecs-preview.exe ./bin/local/ecs-preview-windows-$VERSION.exe
      - mv ./bin/local/ecs-preview ./bin/local/ecs-preview-darwin-$VERSION
      - mv ./bin/local/ecs-preview-amd64 ./bin/local/ecs-preview-linux-$VERSION
      - echo "Creating manifest file..."
      - COMMIT_ID=`git rev-parse HEAD`
      - MANIFESTFILE="$COMMIT_ID.manifest"
      - echo ./bin/local/ecs-preview-windows-$VERSION.exe >> $MANIFESTFILE
      - echo ./bin/local/ecs-preview-darwin-$VERSION >> $MANIFESTFILE
      - echo ./bin/local/ecs-preview-linux-$VERSION >> $MANIFESTFILE
    finally:
      - echo "Built artifacts:"
      - ls -lah ./bin/local
      - ./bin/local/ecs-preview-linux-$VERSION --version
artifacts:
  files:
    - '**/*'
